"""add category and image_url to products

Revision ID: 12eb77a37e2d
Revises: b51fa54181e0
Create Date: 2025-08-24 01:07:44.572094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12eb77a37e2d'
down_revision: Union[str, Sequence[str], None] = 'b51fa54181e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
